### ISSUE TITLE
💡提个建议，想法：单纯做一个歌曲网站，太大才小用了，可以全方面介绍阿梓，也别再说 电梓播放器了

### ISSUE THREAD

**Issue by Huxzhi** [cnSchwarzer/azi-stat#1]
虽然我在直播间几乎没有听到过小缘的声音，但是小缘跟阿梓真的有很多相似之处，区别是一个二次元日语歌曲，一个是流行歌曲
小缘的粉丝也做了一个类似的粉丝网站，有几个点还挺好的，https://xiaoyuan.club/

分为 歌曲，直播状态，视频投稿，插画合集，可以将一些B站链接和图片的缩略图做一个集合

![image](https://user-images.githubusercontent.com/49866441/154188678-2cbeabf5-3786-40e0-827e-6e9c95620678.png)

**Comment by reitowo** [comment]
好想法，但我目前没精力，欢迎贡献
